### PR TITLE
Initial Docker image

### PR DESCRIPTION
**Pull request by CalcProgrammer1**
A Dockerfile creates a Docker image based on Debian Bookworm ARM32 with box86 and box64 installed, Steam, and a `user` account.  A script to set up binfmt is also provided.  Build with

`docker build -t arm-gaming .`

Run with

`docker run -it --privileged --network host -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY arm-gaming bash`

### CODE REVIEW

**Comment by Raezroth** [comment]
Since loading armhf libraries was somehow fixed with arm64 olin box86/64. Can we change this to arm64 base?

**Comment by CalcProgrammer1** [comment]
apt install libxcursor1:armhf libxcomposite1:armhf libxdamage1:armhf libxss1:armhf libsdl2-2.0-0:armhf gnutls-bin:armhf libsm6:armhf libxss1:armhf  libxss1 libsdl2-2.0-0 libxtst6:armhf libxtst6 libvorbisfile3:armhf libvorbisfile3 xdg-desktop-portal-gtk libpcre3:armhf libpcre3

**Comment by CalcProgrammer1** [comment]
image

Ugh, I updated to the latest box86/64 debs, switched to arm64 base image, got persistence figured out, but it's still only getting this far.  Steamwebhelper seems to be crashing.

**Comment by CalcProgrammer1** [comment]
Going to try setting this up using distrobox next.  I think maybe there is some permission issue preventing it from running in my docker setup but distrobox should already set all that stuff up for you.

**Comment by Raezroth** [comment]
So this looks good now. I am going to merge with master. Steam is being a little weird in box86 right now (Atleast in my experience with fresh installs on steam). I know the are a few variables that may help. would need to look into why steamwebhelper is crashing. 

I'll grab some logs on my end. Could you grab some box86 logs of different levels?.

**Pull request merged**
